<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<IsPackable>false</IsPackable>
		<NoWarn>$(NoWarn);xUnit1051;NU1903</NoWarn>
		<OutputType>Exe</OutputType>
	</PropertyGroup>

	<ItemGroup>
		<PackageReference Include="Microsoft.AspNetCore.Mvc.Testing" Version="10.0.0" />
		<PackageReference Include="Microsoft.NET.Test.Sdk" Version="18.0.0" />
		<PackageReference Include="Testcontainers" Version="4.4.0" />
		<PackageReference Include="xunit.v3" Version="3.1.0" />
		<PackageReference Include="xunit.runner.visualstudio" Version="3.1.4" />
	</ItemGroup>

	<ItemGroup>
		<ProjectReference Include="..\..\src\IntegrationHost\IntegrationHost.csproj" />
	</ItemGroup>

	<ItemGroup>
		<Using Include="Xunit" />
		<Using Include="Microsoft.Extensions.Options" />
	</ItemGroup>

</Project>
