<Project>

	<PropertyGroup>
		<Authors>Ben Kloosterman</Authors>
		<Copyright>Copyright (c) 2026 Ben Kloosterman</Copyright>
		<PackageProjectUrl>https://github.com/bklooste/config-integration-host</PackageProjectUrl>
		<RepositoryUrl>https://github.com/bklooste/config-integration-host</RepositoryUrl>
		<RepositoryType>git</RepositoryType>
		<PublishRepositoryUrl>true</PublishRepositoryUrl>
		<EmbedUntrackedSources>true</EmbedUntrackedSources>
		<TargetFramework>net10.0</TargetFramework>
		<Nullable>enable</Nullable>
		<ImplicitUsings>enable</ImplicitUsings>
		<ContinuousIntegrationBuild Condition="'$(GITHUB_ACTIONS)' == 'true'">true</ContinuousIntegrationBuild>
	</PropertyGroup>

	<ItemGroup>
		<PackageReference Include="Nerdbank.GitVersioning" Version="3.10.94" PrivateAssets="all" />
	</ItemGroup>

</Project>
